name: Update Master

on:
  push:
    paths-ignore:
      - '**.md'
      - '**/pluginmaster.json'

    branches:
      - main

  schedule:
    - cron:  '0 0 * * *'

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    concurrency: staging
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Restore mtime
        uses: chetan/git-restore-mtime-action@v1

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Update PluginMaster
        run: python update.py

      - name: Push PluginMaster
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Regenerate PluginMaster